name: CI Pipelin

on:
  push:
    branches:
      - main
      - babysitting
      - experiment
      - 'feature/**'
      - 'hotfix/**'

jobs:

  main:
    if: github.ref == 'refs/heads/main'
    uses: level4cloud-org/devops_library/.github/workflows/ci.yaml@main
    with:
      input_param: "Hello World"
    secrets: inherit