name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  main:
    if: startsWith(github.ref, 'refs/heads/main')
    uses: level4cloud-org/devops_library/.github/workflows/ci.yaml@main
    secrets: inherit
    with:
      PROJECT_NAME: "MLOps"
      INPUT_PARAM: "Hello World - main snyk"
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}